#!/bin/sh
# Installs the tools this course's labs use, at the versions of the LearnSome.tech lab sandbox, on x86-64
# Ubuntu: the dev container (Dockerfile) and CI (.github/workflows/check.yml) both run it, as root.
# `install-tools.sh ci` leaves out the Linux userland the labs call, which CI does not need.
# Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
set -eu
if [ "$(uname -m)" != x86_64 ]; then
  echo "install-tools.sh: x86-64 Linux only (Codespaces, GitHub Actions); elsewhere install the tools yourself" >&2
  exit 1
fi
mode=${1:-full}
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fetch() { curl -fsSL --retry 3 "$1" -o "$2" && echo "$3  $2" | sha256sum -c - >/dev/null; }

export DEBIAN_FRONTEND=noninteractive
apt-get -o Acquire::Retries=5 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update -q
apt-get install -y -q --no-install-recommends bash git unzip xz-utils ca-certificates curl
rm -rf /var/lib/apt/lists/*
mkdir -p /opt/lab

# Python 3.14.7
fetch 'https://github.com/astral-sh/python-build-standalone/releases/download/20260924/cpython-3.14.7%2B20260924-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz' "$tmp/python.tgz" bd0d0568ccded07bbf1c87727230dc5dd0187e706a87da23c4de78388a229b78
mkdir -p /opt/python && tar -xzf "$tmp/python.tgz" -C /opt/python --strip-components=1
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python3
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python

# Go 1.27.1
fetch 'https://go.dev/dl/go1.27.1.linux-amd64.tar.gz' "$tmp/go.tgz" 63d339f0da5ab53635a56f2490a7984dfe12dfcff22ad749f63edaf590168445
mkdir -p /opt/go && tar -xzf "$tmp/go.tgz" -C /opt/go --strip-components=1
ln -sf /opt/go/bin/go /usr/local/bin/go
ln -sf /opt/go/bin/gofmt /usr/local/bin/gofmt
if [ "$mode" != ci ]; then
  # The standard library prebuilt with the sandbox's settings, as its image has it: `go run` then fits the
  # time limit. GOCACHE points here in the dev container.
  mkdir -p /opt/lab/go-cache
  GOCACHE=/opt/lab/go-cache GOPATH="$tmp/gopath" GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off CGO_ENABLED=0 GOFLAGS=-buildvcs=false /opt/go/bin/go build std
  chmod -R a+rwX /opt/lab/go-cache
fi

# The toolchains also under /opt/lab/bin, the sandbox's own PATH entry
mkdir -p /opt/lab/bin
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python3
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python
ln -sf /opt/go/bin/go /opt/lab/bin/go
ln -sf /opt/go/bin/gofmt /opt/lab/bin/gofmt
